; PlatformIO Project Configuration File — Smart Speaker 2.1 Firmware
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    fastled/FastLED @ ^3.7.0
    z3t0/IRremote @ ^4.4.0
    h2zero/NimBLE-Arduino @ ^1.4.1
    pschatzmann/ESP32-A2DP @ ^1.8.5

build_flags =
    -D CORE_DEBUG_LEVEL=3
